DECLARE @e1 TABLE (num INT);
INSERT INTO @e1
    SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL 
    SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL 
    SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9;

DECLARE @e2 TABLE (num INT);
INSERT INTO @e2
	SELECT a.num*100+b.num*10+c.num AS num 
	FROM @e1 AS a 
	CROSS JOIN @e1 AS b 
	CROSS JOIN @e1 AS c; 
 -- 10*10*10

DECLARE @e3 TABLE (num INT);
INSERT INTO @e3
	SELECT a.num*1000+b.num AS num 
	FROM @e2 AS a 
	CROSS JOIN @e2 AS b; 
 --1000*1000
SELECT * FROM @e3 ORDER BY num